name: order-sample
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  orders-api:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      Rabbit__ConnectionString: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network
  
  inventory-api:
    build:
      context: .
      dockerfile: InventoryService/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      Rabbit__ConnectionString: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
          condition: service_healthy
      database:
        condition: service_healthy
    ports:
      - "8089:8080"
    networks:
      - app-network
  
  payment-api:
    build:
      context: .
      dockerfile: PaymentService/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      Rabbit__ConnectionString: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
      database:
        condition: service_healthy
    ports:
      - "8087:8080"
    networks:
      - app-network

  database:
    image: postgres:18.0-alpine3.21
    container_name: Database
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - order_microservices_postgres_volume:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  inventory-worker:
    build:
      context: .
      dockerfile: InventoryWorker/Dockerfile
    environment:
      Rabbit__ConnectionString: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  order_microservices_postgres_volume: